# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing begin"
      - run: npm install
      - run: npm test
hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "helllooooo!"
workflows:
  # Name the workflow "welcome"
  version: 2
    # Run the welcome/run job in its own container
  build_test_and_lint
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere
